
name: 'Docker build - Beta Release'

on:
    push:
        branches:
            - beta
    release:
        types:
            -  created

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
        -   name: Echo github.ref
            run: echo ${{ github.ref }}
        -
            name: Checkout
            uses: actions/checkout@v1
        -
            name: Dockerhub login
            env:
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            run: |
                echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
        -
            name: Set up Docker Buildx
            id: buildx
            uses: crazy-max/ghaction-docker-buildx@v1
            with:
                version: latest
        -
            name: Build dockerfile (with push)
            run: |
                docker buildx build \
                --platform=linux/amd64,linux/arm/v7,linux/arm/v6 \
                --output "type=image,push=true" \
                --file ./Dockerfile . \
                --tag bloody2k/rpi_monitor:beta
                --tag bloody2k/rpi_monitor:${{ github.ref }}

